apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: economic-similarity-cash-flows
    image: gcr.io/kaniko-project/executor:debug
    env:
      - name: WHEN
        value: 2022-04-01
    args: [ "--context=git://github.com/yakmanyakmanyedatsme/economic-similarity",
            "--destination=yakmanyakmanyedatsme/economic-similarty-cash-flows:1.0.0",
            "--WHEN=$(WHEN)"] # replace with your dockerhub account
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
      - name: dockerfile-storage
        mountPath: /test-pd
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: dockerfile-storage
      gcePersistentDisk:
        pdName: my-data-disk
        fsType: ext4