apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: economic_similarity_cash_flows
    image: gcr.io/kaniko-project/executor:debug
    args: [ "--context=git://github.com//yakmanyakmanyedatsme/economic-similarity",
            "--destination=yakmanyakmanyedatsme/economic_similarity_cash_flows:1.0.0"] # replace with your dockerhub account
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
      - name: dockerfile-storage
        mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: dockerfile-storage
      gcePersistentDisk:
        pdName: my-data-disk
        fsType: ext4